### ISSUE TITLE
AttributeError: 'Ethernet' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Irondev25** [EONRaider/Packet-Sniffer#1]
I am on ubuntu based machine, using python 3.8.5

ran the script 
`sudo python3 packet_sniffer.py -i wlo1 -d `

```
Traceback (most recent call last):
  File "packet_sniffer.py", line 153, in <module>
    sniff(cli_args)
  File "packet_sniffer.py", line 138, in sniff
    packet_sniffer.execute()
  File "packet_sniffer.py", line 44, in execute
    setattr(self, protocol.lower(), protocol)
AttributeError: 'Ethernet' object has no attribute 'lower'
```

**Comment by EONRaider** [comment]
True. Thanks for pointing that out. I had renamed a certain variable without noticing it was already in use. Code is working properly now.
